import { createHash } from 'node:crypto';
import type { CalleCallStatus, JsonSchema } from '@dial/schemas';
import { maskPhone } from '@dial/domain';
import {
  type CallProvider,
  type ProviderCallRequest,
  type ProviderCallSnapshot,
} from './provider.js';

/**
 * Deterministic stand-in used ONLY when TEST_PROVIDER=mock.
 *
 * This exists so the orchestration, comparison and UI paths can be tested
 * end-to-end without ringing a real business. It is not a fallback: the config
 * layer refuses to boot with TEST_PROVIDER=real and no API key, so the app can
 * never quietly serve fake calls while claiming to place real ones.
 *
 * It deliberately produces the *unhappy* outcomes too -- no answer, voicemail,
 * refusals, and null structured results -- because those are the paths most
 * likely to be wrong, and a fake that only ever succeeds would hide them.
 */
export class FakeCallProvider implements CallProvider {
  readonly name = 'fake' as const;
  readonly placesRealCalls = false;

  private readonly calls = new Map<string, ProviderCallSnapshot>();
  /** Idempotency key -> call id, mirroring CALL-E's own replay behaviour. */
  private readonly byIdempotencyKey = new Map<string, string>();

  async create(request: ProviderCallRequest): Promise<ProviderCallSnapshot> {
    const existingId = this.byIdempotencyKey.get(request.idempotencyKey);
    if (existingId) {
      // A replayed key returns the original call rather than dialling again.
      return this.calls.get(existingId)!;
    }

    const seed = hashToUnit(request.idempotencyKey);
    const providerCallId = `fake_${createHash('sha256').update(request.idempotencyKey).digest('hex').slice(0, 20)}`;

    const snapshot = this.buildSnapshot(providerCallId, request, seed);
    this.calls.set(providerCallId, snapshot);
    this.byIdempotencyKey.set(request.idempotencyKey, providerCallId);
    return snapshot;
  }

  async get(providerCallId: string): Promise<ProviderCallSnapshot> {
    const snapshot = this.calls.get(providerCallId);
    if (!snapshot) {
      const error = new Error(`Unknown call ${providerCallId}`) as Error & { code: string };
      error.code = 'not_found';
      throw error;
    }
    return snapshot;
  }

  private buildSnapshot(
    providerCallId: string,
    request: ProviderCallRequest,
    seed: number,
  ): ProviderCallSnapshot {
    const now = new Date().toISOString();
    const masked = maskPhone(request.phone);

    // Outcome mix chosen to exercise every downstream branch.
    let status: CalleCallStatus = 'completed';
    let structuredResult: Record<string, unknown> | null = null;
    let failureCode: string | null = null;
    let failureMessage: string | null = null;
    let attemptStatus: 'completed' | 'failed' = 'completed';
    let summary = 'Spoke to the business and captured an answer.';

    if (seed < 0.12) {
      status = 'failed';
      failureCode = 'no_answer';
      failureMessage = 'Nobody picked up after several rings.';
      attemptStatus = 'failed';
      summary = 'No answer.';
    } else if (seed < 0.2) {
      status = 'completed';
      summary = 'Reached voicemail; no message left.';
      structuredResult = null; // voicemail yields nothing schema-valid
    } else if (seed < 0.28) {
      status = 'completed';
      summary = 'Reached a person, but they would not give a figure over the phone.';
      structuredResult = this.refusal(request.resultSchema);
    } else {
      structuredResult = this.answer(request.resultSchema, seed);
    }

    return {
      providerCallId,
      status,
      structuredResult,
      summary,
      taskCompleted: structuredResult !== null,
      completionConfidence:
        structuredResult === null ? null : { score: 0.6 + seed * 0.35, label: seed > 0.6 ? 'high' : 'medium' },
      evidence:
        structuredResult === null
          ? []
          : ['Quoted figure stated on the call.', 'Availability confirmed verbally.'],
      attempts: [
        {
          id: `${providerCallId}_a1`,
          phoneMasked: masked,
          status: attemptStatus,
          startedAt: now,
          completedAt: now,
          summary,
          transcript: [
            {
              offsetSeconds: 0,
              speaker: 'unknown',
              text: 'SIMULATED CALL — no telephone call was placed and no business was contacted. This transcript is generated by the dry-run provider.',
            },
            {
              offsetSeconds: 0,
              speaker: 'bot',
              text: 'Hello, I am an AI assistant calling on behalf of a customer.',
            },
            { offsetSeconds: 4, speaker: 'user', text: 'Hi, go ahead.' },
          ],
          failureCode,
          failureMessage,
        },
      ],
      failureCode,
      failureMessage,
      createdAt: now,
      completedAt: now,
    };
  }

  /** Fills whichever schema was requested, so any call family works. */
  private answer(schema: JsonSchema, seed: number): Record<string, unknown> {
    const props = schema.properties ?? {};
    const out: Record<string, unknown> = {};
    const price = Math.round((70 + seed * 180) * 100) / 100;

    for (const [key, def] of Object.entries(props)) {
      if (key === 'confidence') out[key] = seed > 0.6 ? 'high' : 'medium';
      else if (key === 'evidence_summary') out[key] = 'They stated the figure and availability on the call.';
      else if (key === 'business_name') out[key] = 'Simulated Business';
      else if (key === 'currency') out[key] = 'EUR';
      else if (def.type === 'number' || def.type === 'integer') {
        out[key] = key.includes('callout') ? Math.round(seed * 40) : key.includes('party') ? 4 : price;
      } else if (def.enum) {
        const options = def.enum.filter((v) => v !== 'unknown');
        out[key] = options[Math.floor(seed * options.length)] ?? def.enum[0];
      } else if (def.type === 'string') {
        out[key] = seed > 0.5 ? 'Same day, subject to parts.' : 'Within 24 hours.';
      }
    }
    return out;
  }

  /** A genuine "they would not say" -- required fields present, answers unknown. */
  private refusal(schema: JsonSchema): Record<string, unknown> {
    const out: Record<string, unknown> = {};
    for (const [key, def] of Object.entries(schema.properties ?? {})) {
      if (key === 'confidence') out[key] = 'low';
      else if (key === 'evidence_summary') out[key] = 'They declined to quote over the phone.';
      else if (def.enum?.includes('unknown')) out[key] = 'unknown';
    }
    return out;
  }
}

/** Stable 0..1 value from a key, so a given call always behaves the same way. */
function hashToUnit(key: string): number {
  const digest = createHash('sha256').update(key).digest();
  return digest.readUInt32BE(0) / 0xffffffff;
}
